language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations activity blog members gallery status tasks
  - python manage.py migrate
  - python manage.py test
