language: python
python:
  - "3.6"
before_install:
  - cp framework/sample_local_settings.py framework/local_settings.py
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations activity blog gsoc members status pages
  - python manage.py migrate
  - python manage.py test
