language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations activity blog gsoc members status pages
  - python manage.py migrate
  - python manage.py test
